### ISSUE TITLE
Amalgam のパッケージ名が違う？

### ISSUE THREAD

**Issue by rnitame** [nohana/Laevatein#67]
#65 の続きです 🙇 
以下のようなエラーが吐かれて選択画面が起動しません。

```
 java.lang.NoClassDefFoundError: Failed resolution of: Lcom/amalgam/os/BundleUtils;
        at com.laevatein.ui.PhotoSelectionActivity.<clinit>(PhotoSelectionActivity.java:63)
        at com.laevatein.SelectionSpecBuilder.forResultWithTransition(SelectionSpecBuilder.java:411)
        at com.laevatein.SelectionSpecBuilder.forResult(SelectionSpecBuilder.java:366)
```

PhotoSelectionActivity を見てみたら、import されているパッケージ名が異なっているように見えました。
https://github.com/nohana/Laevatein/blob/5556a75e48bac1c915063d7947a169d81329cc8d/laevatein/src/main/java/com/laevatein/ui/PhotoSelectionActivity.java#L32-L33

ご確認のほど、よろしくお願いします！

**Comment by hiroyuki-seto** [comment]
Android Studio3以降をお使いかと思われますが、
`implementation 'jp.co.nohana:Laevatein:2.1.2@aar'`
を
`implementation 'jp.co.nohana:Laevatein:2.1.2`
に変更すると解決したりしないでしょうか？

**Comment by rnitame** [comment]
いけました！ありがとうございます…！

**Comment by hiroyuki-seto** [comment]
お手数をおかけいたしました。
README更新します...
